-- CreateTable
CREATE TABLE "Submission" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "full_name" TEXT NOT NULL,
    "company_name" TEXT,
    "role_position" TEXT,
    "work_email" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "website_links" TEXT,
    "services" TEXT NOT NULL,
    "services_other" TEXT,
    "video_count_option" TEXT,
    "video_custom_requirement" TEXT,
    "video_usage_platforms" TEXT NOT NULL,
    "has_raw_footage" TEXT,
    "web_services" TEXT NOT NULL,
    "chatbot_platform" TEXT,
    "has_existing_website" TEXT,
    "existing_website_link" TEXT,
    "website_purpose" TEXT,
    "brand_services" TEXT NOT NULL,
    "brand_name" TEXT,
    "brand_files_link" TEXT,
    "ad_goal" TEXT,
    "ad_budget" TEXT,
    "ad_target_locations" TEXT,
    "favorite_colors" TEXT,
    "business_model" TEXT,
    "future_vision" TEXT,
    "inspiration_brands" TEXT,
    "how_heard" TEXT
);
